// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterPurifierTimeAlert.Server.Context;

#nullable disable

namespace WaterPurifierTimeAlert.Server.Migrations
{
    [DbContext(typeof(PurifierContext))]
    [Migration("20260522020000_AddPushSubscription")]
    partial class AddPushSubscription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("WaterPurifierTimeAlert.Server.Context.Entity.ExchangeFilter", b =>
                {
                    b.Property<string>("FilterName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastExchnageDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FilterName");

                    b.ToTable("ExchangeFilter", (string)null);
                });

            modelBuilder.Entity("WaterPurifierTimeAlert.Server.Context.Entity.PushSubscription", b =>
                {
                    b.Property<string>("Endpoint")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Auth")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("P256dh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Endpoint");

                    b.HasIndex("UserEmail");

                    b.ToTable("PushSubscription", (string)null);
                });

            modelBuilder.Entity("WaterPurifierTimeAlert.Server.Context.Entity.FilterType", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpireTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("FilterType", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
