// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterPurifierTimeAlert.Server.Context;

#nullable disable

namespace WaterPurifierTimeAlert.Server.Migrations
{
    [DbContext(typeof(PurifierContext))]
    [Migration("20260429135605_INIT")]
    partial class INIT
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("WaterPurifierTimeAlert.Server.Context.Entity.ExchangeFilter", b =>
                {
                    b.Property<string>("FilterName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastExchnageDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FilterName");

                    b.ToTable("ExchangeFilter");
                });

            modelBuilder.Entity("WaterPurifierTimeAlert.Server.Context.Entity.FilterType", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpireTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("FilterType");
                });
#pragma warning restore 612, 618
        }
    }
}
