// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WaterPurifierTimeAlert.Context;

#nullable disable

namespace WaterPurifierTimeAlert.Migrations
{
    [DbContext(typeof(PurifierContext))]
    partial class PurifierContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("WaterPurifierTimeAlert.Context.Entity.ExchangeFilter", b =>
                {
                    b.Property<string>("FilterName")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastExchnageDate")
                        .HasColumnType("TEXT");

                    b.HasKey("FilterName");

                    b.ToTable("ExchangeFilter");
                });

            modelBuilder.Entity("WaterPurifierTimeAlert.Context.Entity.FilterType", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ExpireTime")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Name");

                    b.ToTable("FilterType");
                });
#pragma warning restore 612, 618
        }
    }
}
