---
ContentRootPath: 
# WebRootPath: "ClientApp"
# WebHttpPort: 80
# WebHttpsPort: 443
# ServerCertificate: ""
# ServerCertificatePassword: ""
# CertificateChain: ","
# IncludeCipherSuites: ","
DbPath: 
# VapidSubject:
# VapidPublicKey:
# VapidPrivateKey:
# AlertScheduleExpression: "0 0 9 * * ?"
