---
ContentRootPath: # Absolute Path
# WebRootPath: "ClientApp" # Relative Path ${ContentRootPath}/${WebRootPath}
# WebHttpPort: 80
# WebHttpsPort: 443
# ServerCertificate: "" # Absolute Path
# ServerCertificatePassword: ""
# CertificateChain: ","
# IncludeCipherSuites: ","
DbPath: # Absolute Path ex) purifer.db
# VapidSubject:
# VapidPublicKey:
# VapidPrivateKey:
# AlertScheduleExpression: "0 0 9 * * ?"
