---
ContentRootPath: 
# WebRootPath: "ClientApp"
# WebHttpPort: 80
# WebHttpsPort: 443
# ServerCertificate: ""
# ServerCertificatePassword: ""
# CertificateChain: ","
# IncludeCipherSuites: ","
DbPath: 